apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: bulletin-board-chart
    meta.helm.sh/release-namespace: demo
  creationTimestamp: "2022-05-21T05:20:21Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: bulletin-board-chart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bulletin-board
    app.kubernetes.io/version: v0.3
    helm.sh/chart: bulletin-board-0.1.0
  name: bulletin-board-chart
  namespace: demo
  resourceVersion: "64103"
  uid: 0f3af418-d397-4c88-b0e8-c2cd771ee9a2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: bulletin-board-chart
      app.kubernetes.io/name: bulletin-board
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: bulletin-board-chart
        app.kubernetes.io/name: bulletin-board
    spec:
      containers:
      - image: muadham/bulletin-app:v0.3
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: bulletin-board
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            drop:
            - ALL
          runAsGroup: 5000
          runAsNonRoot: true
          runAsUser: 5000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bulletin-board-chart
      serviceAccountName: bulletin-board-chart
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-05-21T05:20:40Z"
    lastUpdateTime: "2022-05-21T05:20:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-05-21T05:20:21Z"
    lastUpdateTime: "2022-05-21T05:20:40Z"
    message: ReplicaSet "bulletin-board-chart-5d6f45c47f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
