apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"jenkins-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"8Gi"},"hostPath":{"path":"/data/jenkins/"},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"jenkins-pv"}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2022-05-20T02:33:56Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: jenkins-pv
  resourceVersion: "2491"
  uid: 26349c1f-1e1d-42c8-8670-f00010423168
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins
    namespace: jenkins
    resourceVersion: "2482"
    uid: 77d426c5-bf36-4513-9224-d19a9ed99575
  hostPath:
    path: /data/jenkins/
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-pv
  volumeMode: Filesystem
status:
  phase: Bound
