apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-05-20T02:28:34Z"
  name: default
  namespace: jenkins
  resourceVersion: "1664"
  uid: 2d1e8206-600e-41fb-b4f1-09c8b369e663
secrets:
- name: default-token-8k2vp
