pipeline {
    agent {
        kubernetes {
            label 'jenkinsrun'
      defaultContainer 'builder'
      yaml """
apiVersion: v1
kind: Pod
metadata:
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: docker-credentials
          items:
            - key: .dockerconfigjson
              path: config.json
"""
        }
    }

    

    stages {

        

        stage('Clone repository') {
            agent any
            steps{
                checkout scm
            }
        }

        stage('Run change script') {
            agent any
            steps {
                sh '''
                    chmod 777 change.sh
                    ./change.sh
                '''
            }
        }

        stage('Build and push with Kaniko') {
          steps {
            container(name: 'kaniko', shell: '/busybox/sh') {
              withEnv(['PATH+EXTRA=/busybox']) {
               
                sh '''#!/busybox/sh -xe
                  /kaniko/executor \
                    --dockerfile Dockerfile \
                    --customPlatform=linux/amd64 \
                    --context `pwd`/ \
                    --verbosity debug \
                    --insecure \
                    --skip-tls-verify \
                    --destination muadham/bulletin-app:v0.3
                '''
              }
            }
          }
        }
        

    }
}
