apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-05-20T02:17:42Z"
  name: disruption-controller
  namespace: kube-system
  resourceVersion: "296"
  uid: 61c5866e-decb-4ef3-9313-836b6e03c41b
secrets:
- name: disruption-controller-token-cl7tn
