apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-05-20T02:17:41Z"
  name: namespace-controller
  namespace: kube-system
  resourceVersion: "267"
  uid: f0912d30-2719-43cd-816f-ddb872496461
secrets:
- name: namespace-controller-token-dlnt2
