apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-05-20T02:17:41Z"
  name: service-account-controller
  namespace: kube-system
  resourceVersion: "264"
  uid: 3d3ff989-90e8-4094-9d28-24f237f38f43
secrets:
- name: service-account-controller-token-r8t6s
