apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-05-20T02:17:41Z"
  name: token-cleaner
  namespace: kube-system
  resourceVersion: "280"
  uid: c1b19aaa-a91e-438d-94ba-17f518c3e2d3
secrets:
- name: token-cleaner-token-ghh9z
